### ISSUE TITLE
TGMM import fails with NullPointerException

### ISSUE THREAD

**Issue by erjel** [fiji/MaMuT#22]
Hi,

I tried to visualized TGMM tracking results with MaMuT. However, as soon as I press the button `Import TGMM results in MaMuT` a new Fiji Exception window pops-up with the error message:

```
(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52p; Java 1.8.0_66 [64-bit]; Windows 10 10.0; 82MB of 24450MB (<1%)
 
java.lang.NullPointerException
	at fiji.plugin.mamut.ImportTGMMAnnotationPlugin_.showDialog(ImportTGMMAnnotationPlugin_.java:151)
	at fiji.plugin.mamut.ImportTGMMAnnotationPlugin_.run(ImportTGMMAnnotationPlugin_.java:136)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)
```

Can you help me using MaMuT for reviewing the TGMM results?

**Comment by tinevez** [comment]
It looks like the importer cannot find the XML/HDF5 generated with BigDataViewer.
Did you specify it correctly?

**Comment by erjel** [comment]
I just reinstalled Fiji and the MaMuT Plugin. Now the exception does not occur anymore. Thank you for your quick response.
